In [1]:
from flask import Flask, request, render_template
from model import Model
from model import LabelEncoder
import numpy as np
import os
print(os.getcwd())

c:\Users\yang_\OneDrive\Desktop\ai300\AI300_Projects\may24-team09\src


In [2]:
os.chdir('..')
print(os.getcwd())

c:\Users\yang_\OneDrive\Desktop\ai300\AI300_Projects\may24-team09


In [3]:
model = Model()
label_encoders = LabelEncoder()

In [4]:
form_input = {
    'tenure_months': 2,
    'total_monthly_fee': 111,
    'has_internet_service': 'Yes',
    'contract_type': 'Month-to-Month',
    'num_referrals': 0,
    'num_dependents': 0,
    'married': 'No',
    'has_online_security': 'No',
    'stream_movie': 'Yes',
    'stream_music': 'Yes',
    'age': 21
}

In [5]:
encoded_inputs = label_encoders.transform(form_input)

In [6]:
encoded_inputs

{'tenure_months': 2,
 'total_monthly_fee': 111,
 'has_internet_service': 1,
 'contract_type': 0,
 'num_referrals': 0,
 'num_dependents': 0,
 'married': 0,
 'has_online_security': 0,
 'stream_movie': 1,
 'stream_music': 1,
 'age': 21}

In [7]:
model_inputs = np.array(list(encoded_inputs.values()), dtype=float).reshape(1, -1)
model_inputs

array([[  2., 111.,   1.,   0.,   0.,   0.,   0.,   0.,   1.,   1.,  21.]])

In [8]:
prediction = model.predict(model_inputs)
prediction

array([1])

In [9]:
prediction[0]

1

In [10]:
probabilityy = model.predict_proba(model_inputs)
probabilityy

array([[0.17239213, 0.82760787]], dtype=float32)

In [11]:
probabilityy[0][1]

0.82760787